### ISSUE TITLE
Drivers not working on Ubuntu 22.04 5.19 Kernel

### ISSUE THREAD

**Issue by Niederfuchs** [GloriousEggroll/AVMATRIX-VC12-4K-CAPTURE#3]
Hey, unfortunately I am not professional enough to be able to know what this is about. but I get the following Error Message:
```
===================================================
      HWS Linux Driver Installer
===================================================

Checking for required tools ... Done.
Checking for required packages ... Done.
Checking for previous installation ... None
Beginning install, please wait... 
Installing module ... Running dkms ... Creating symlink /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/source -> /usr/src/HwsUHDX1Capture.ko-1.0.0.230324
Warning: I do not know how to handle modules.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j16 KERNELRELEASE=5.19.0-46-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for HwsUHDX1Capture.ko: 1.0.0.230324 not found
Error! Bad return status for module build on kernel: 5.19.0-46-generic (x86_64)
Consult /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/make.log for more information.

ERROR: DKMS failed to build!

Please check hws_install.log for more details.
If you are experiencing difficulty with this installation
please contact  sales@avmatrix.com
```
The Log File has the following content:
```
DKMS make.log for HwsUHDX1Capture.ko-1.0.0.230324 for kernel 5.19.0-46-generic (x86_64)
Do 13. Jul 13:02:27 CEST 2023
make -C /lib/modules/5.19.0-46-generic/build M=/var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build modules
make[1]: Verzeichnis „/usr/src/linux-headers-5.19.0-46-generic“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  CC [M]  /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.o
/var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.c: In function ‘hws_audio_register’:
/var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.c:3419:13: error: implicit declaration of function ‘snd_dma_continuous_data’ [-Werror=implicit-function-declaration]
 3419 |             snd_dma_continuous_data(GFP_KERNEL),
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.c:3419:13: warning: passing argument 3 of ‘snd_pcm_lib_preallocate_pages_for_all’ makes pointer from integer without a cast [-Wint-conversion]
 3419 |             snd_dma_continuous_data(GFP_KERNEL),
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             |
      |             int
In file included from /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws.h:22,
                 from /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.c:11:
./include/sound/pcm.h:1222:59: note: expected ‘void *’ but argument is of type ‘int’
 1222 |                                           int type, void *data,
      |                                                     ~~~~~~^~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:257: /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build/hws_video.o] Fehler 1
make[1]: *** [Makefile:1857: /var/lib/dkms/HwsUHDX1Capture.ko/1.0.0.230324/build] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-5.19.0-46-generic“ wird verlassen
make: *** [Makefile:18: all] Fehler 2

```
It would be awesome if you guys could resolve this.
Thank You kindly !

**Comment by SoenkeGraf** [comment]
Ubuntu 22.04 has moved to Kernel 6.2 - which resolved the 5.19 kernel issue. File closed.
